name: Efetuar deploy dos manifestos Terraform

on:
  push:
    branches:
    - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  tf_apply:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ./terraform

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "0.14.9"

    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var aws_access_key="$AWS_ACCESS_KEY_ID" -var aws_secret_key="$AWS_SECRET_ACCESS_KEY"

